# Generated by Django 3.0.6 on 2020-06-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naipe', models.CharField(choices=[('C', 'Copas'), ('E', 'Espadas'), ('O', 'Ouros'), ('P', 'Paus')], default='C', max_length=1)),
                ('valor', models.CharField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 'J'), (12, 'Q'), (13, 'K'), (14, 'A')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=2)),
                ('cartas', models.ManyToManyField(blank=True, related_name='lista_cartas', to='core.Carta')),
            ],
        ),
    ]
